### PR TITLE
Fixes policy configuration state transitions in `AuthorizationService`

### PR DESCRIPTION
**Pull request by avpinchuk**
Error case: https://github.com/eclipse-ee4j/glassfish/issues/24514

Signed-off-by: Alexander Pinčuk <alexander.v.pinchuk@gmail.com>

### CODE REVIEW

**Comment by arjantijms** [comment]
>  what you think about that?

I'm not entirely sure. Always getting the `PolicyConfiguration` freshly from the `PolicyConfigurationFactory` using the `String, Boolean` method, has the side-effect of always transitioning the state to OPEN again. In other words, the state machine could just as well be not there, if it's always set to OPEN.

Maybe we only need to explicitly open it again after `webBundleDescriptor.isPolicyModified()` is true in `com.sun.enterprise.security.ee.SecurityDeployer.commitWebPolicy(WebBundleDescriptor)`?

As an extra observation; only a policy change during startup should actually trigger the `release()` call, but in `com.sun.web.security.RealmAdapter.updateWebSecurityManager()` we see a `release()` followed by a `destroy()`, which is somewhat in conflict with the comments. 

Otherwise `release()` might also be a good place to re-open the policy configuration again.

**Comment by avpinchuk** [comment]
Thank you for reply. I think about that. But, in `AuthorizationService.removeStatementFromPolicy` method if policy in service

```java
 boolean inService = factory.inService(contextId);
```

we always get an exception here

```java
 policyConfiguration.removeUncheckedPolicy();
 policyConfiguration.removeExcludedPolicy();
```

And if policy is in open state, cleanup succesfull, but we newer call the `Policy.refresh`:

```java
// Refresh policy if the context was in service
if (inService) {
    policy.refresh();
}
```

**Comment by arjantijms** [comment]
I just checked GF 6 (pre-exousia), and it indeed opens the policy in the release method:

https://github.com/eclipse-ee4j/glassfish/blob/a4f64c05f9b278e61ccac1bc80f8f98c339cb0e5/appserver/security/core-ee/src/main/java/com/sun/enterprise/security/web/integration/WebSecurityManager.java#L561

```java
    public void release() throws PolicyContextException {
        boolean wasInService = getPolicyFactory().inService(CONTEXT_ID);
        
        // Policy is implicitly opened here 
        PolicyConfiguration config = getPolicyFactory().getPolicyConfiguration(CONTEXT_ID, false);
        WebPermissionUtil.removePolicyStatements(config, wbd);
        
        // Refresh policy if the context was in service
        if (wasInService) {
            Policy.getPolicy().refresh();
        }
  
        PermissionCacheFactory.removePermissionCache(uncheckedPermissionCache);
        uncheckedPermissionCache = null;
        wsmf.getManager(CONTEXT_ID, null, true);
    }
```

When integrating Exousia, that bit was missed it seems:

```java
    public void release() throws PolicyContextException {

        // Effectively does "wasInService" to "Policy.getPolicy().refresh();"
        // but does't do getPolicyFactory().getPolicyConfiguration(CONTEXT_ID, false);
        authorizationService.removeStatementsFromPolicy(null);

        PermissionCacheFactory.removePermissionCache(uncheckedPermissionCache);
        uncheckedPermissionCache = null;
        webSecurityManagerFactory.getManager(contextId, true);
    }
```

So updating `AuthorizationService.removeStatementFromPolicy` seems the most logical option. Indeed, it won't refresh there. 

But in `com.sun.enterprise.security.ee.SecurityDeployer.loadWebPolicy(WebBundleDescriptor, boolean)`  it executes:

```java
webSecurityManagerFactory.createManager(webBundleDescriptor, true, serverContext);
```

Which would ultimately create a new `AuthorizationService` that does all the scanning from start (and therefore implicitly  "refreshes" the policy:

```java
authorizationService = new AuthorizationService(
            getContextID(webBundleDescriptor),
            () -> SecurityContext.getCurrent().getSubject(),
            null);

        authorizationService.setConstrainedUriRequestAttribute(CONSTRAINT_URI);
        authorizationService.setRequestSupplier(
            () -> (HttpServletRequest) webSecurityManagerFactory.pcHandlerImpl.getHandlerData().get(HTTP_SERVLET_REQUEST));

        authorizationService.addConstraintsToPolicy(
            getConstraintsFromBundle(webBundleDescriptor),
            webBundleDescriptor.getRoles()
               .stream()
               .map(e -> e.getName())
               .collect(toSet()),
            webBundleDescriptor.isDenyUncoveredHttpMethods(),
            getSecurityRoleRefsFromBundle(webBundleDescriptor));
```

**Comment by avpinchuk** [comment]
@arjantijms, thank you for detailed explanation. Review, please.

**Review by arjantijms — APPROVED** [review]
LGTM!

**Pull request merged**
